### ISSUE TITLE
elem.roundSlider is not a function!

### ISSUE THREAD

**Issue by dgiac85** [dtruel/angular-round-slider#1]
Hi, i'm Giacomo an italian developer, i'm trying your directive, when i've found this error in the directive's code!
do you have some hints about this error?

Thanks for attention

**Comment by dtruel** [comment]
I do not see the error.  Please let me know what it is

**Comment by adriela** [comment]
include jquery.js and remplace "elem" with "$(elem)"

**Comment by dtruel** [comment]
Hm, I think @adriela  may be right that you need to include jquery
