### ISSUE TITLE
Get "sliderModal" value in custom controller

### ISSUE THREAD

**Issue by ragunathans** [dtruel/angular-round-slider#2]
How to get sliderModal value in my custom angular controller.

I got the sliderModal in HTML and I can't able to access that scope in my custom controller

**Comment by dtruel** [comment]
You may just have a typo - it is "sliderModel" in the demo, not "sliderModal"

You just put in whatever you want to bind in the "value" attribute like this:

```html
<round-slider value="sliderModel" radius="200"></round-slider>
```

then in your controller, 
```javascript
//get
console.log($scope.sliderModel)
//set
$scope.sliderModel = 20;
```

**Comment by ragunathans** [comment]
Sorry that is my mistake.

`console.log($scope.sliderModel)` is showing **undefined** in console.

I want to get this value in my custom controller.

**Comment by dtruel** [comment]
You may have it in an ng-if statement or something like that.  If so, you need to pre-initialize the value of the slider in your scope,  or do something like `data.slider` for the model.

**Comment by ragunathans** [comment]
No. I have only one slider on my page. So I don't use ng-if or ng-repeat. If I initialize the `sliderModel` in my controller then the value is not updated when we change the slider

**Comment by dtruel** [comment]
I made a demo here:

http://turbobuilt.com/demos/angular-round-slider/

It would help if you would post some code.

You could try doing this in your controller:

$scope.data = {}


then in your html roundslider, set  `value="data.sliderModel"`

then console.log(data.sliderModel) in your app.
